### ISSUE TITLE
無法在系計中電腦部屬

### ISSUE THREAD

**Issue by Joechiaotung** [yungyuc/turgon#4]
當我下make指令資工系計中時，他卡在這裡
![image](https://user-images.githubusercontent.com/33175924/68195945-cee82680-fff2-11e9-8969-0622717f0b9f.png)

**Comment by yungyuc** [comment]
@Joechiaotung , thanks for posting it as requested.  You are not building in a correct directory.  Please go to `spacetime/`, where the code resides.  `writing/` is for the notes in TeX, which depends on the code.

And when you are reporting a build issue, it will be useful to be specific.  I think only users of your department computer center knows how their computers are configured, and I certainly don't have a clue.  Being a user, you can inspect the configuration and environment and show what you see.  When you are in the correct directory, the system information will help.

Please use English on GitHub, and use plain text whenever you can.  It's not easy to reuse images, so we avoid it unless we really want to show graphics.

I am closing this issue so that you can use English to create another one.
